"""UAD 3.6 appraisal XML validator (URAR).

Rules come from rules.json, generated by scripts/uad/build_rules.py from the GSE-published
Appendix A-1 (URAR Delivery Specification) and Appendix H-1 (URAR Compliance Rules).

Checks, in order:
  1. Safe parse (a UAD 3.6 ZIP package is accepted and its one XML file is used): well-formed XML, no DOCTYPE or entity declarations, MISMO MESSAGE root in the MISMO
     residential namespace, MISMOReferenceModelIdentifier 3.6.0366, a supported report type.
     Failing any of these is an input error: no report, never charged.
  2. Delivery specification (A-1): every element is a known UAD path, supported enumerations,
     data point formats (boolean, date, datetime, numeric precision and sign, string length),
     required (R) data points inside each container that is present, container cardinality.
  3. Compliance rules (H-1): the rules the build script could translate without interpretation,
     evaluated per instance with three-valued logic. A rule only fires when its condition is
     definitely true; when the file leaves it ambiguous the rule stays quiet.

Verdict: any error (H-1 Fatal, or a delivery specification violation) is FAIL; otherwise any
warning is WARN; otherwise PASS. Structural checks only: a PASS is not UCDP acceptance.
"""
import datetime as dt
import hashlib
import io
import json
import re
import xml.etree.ElementTree as ET
import zipfile
import zlib
from collections import Counter, defaultdict
from pathlib import Path

MISMO_NS = 'http://www.mismo.org/residential/2009/schemas'
RULES = None
MAX_FINDINGS = 500
VA = ('MESSAGE/DOCUMENT_SETS/DOCUMENT_SET/DOCUMENTS/DOCUMENT/DEAL_SETS/DEAL_SET/DEALS/DEAL/SERVICES/SERVICE/'
      'VALUATION/VALUATION_RESPONSE/VALUATION_ANALYSES/VALUATION_ANALYSIS')
PROPERTY = VA + '/PROPERTIES/PROPERTY'
REPORT_ID_PATH = VA + '/VALUATION_REPORT/VALUATION_REPORT_DETAIL/ValuationReportContentIdentifier'
USE_TYPES = ['SubjectProperty', 'SalesComparable', 'LandComparable', 'RentalComparable',
             'GrossRentMultiplierComparable', 'PropertyAnalyzedNotUsed']
# 50 states, DC, territories and freely associated states, and military "states".
STATE_CODES = set('AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC '
                  'ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY DC AS GU MP PR VI UM FM MH PW AA AE AP'.split())
SUPPORTED = {'URAR Delivery Specification': 'URAR'}
UNSUPPORTED = {'Update Report': 'Appraisal Update Report', 'Completion': 'Completion Report'}


class InputError(ValueError):
    """The input is not a UAD 3.6 URAR XML file this validator can audit. Never billed."""


def rules():
    global RULES
    if RULES is None:
        RULES = json.loads((Path(__file__).parent / 'rules.json').read_text('utf-8'))
    return RULES


def local(tag):
    return tag.rsplit('}', 1)[-1] if isinstance(tag, str) else ''


def lcp(a, b):
    n = 0
    while n < min(len(a), len(b)) and a[n] == b[n]:
        n += 1
    return n


# ---------------------------------------------------------------- document model

class Doc:
    def __init__(self, root):
        self.root = root
        self.parent = {}
        self.path = {root: (local(root.tag),)}   # element -> tuple of local names
        self.by_path = defaultdict(list)
        for e in root.iter():                     # document order
            if not isinstance(e.tag, str):
                continue
            p = self.path[e]
            self.by_path['/'.join(p)].append(e)
            for c in e:
                if isinstance(c.tag, str):
                    self.parent[c] = e
                    self.path[c] = p + (local(c.tag),)
        self._xp = {}

    def use_of(self, e):
        """@ValuationUseType of the valuation PROPERTY at or above e, or None."""
        p = self.path[e]
        depth = len(PROPERTY.split('/'))
        if len(p) < depth or '/'.join(p[:depth]) != PROPERTY:
            return None
        while len(self.path[e]) > depth:
            e = self.parent[e]
        return e.get('ValuationUseType')

    def xpath(self, e):
        if e in self._xp:
            return self._xp[e]
        parts = []
        cur = e
        while cur is not None:
            name = local(cur.tag)
            par = self.parent.get(cur)
            if par is not None:
                same = [c for c in par if local(c.tag) == name]
                parts.append(f'{name}[{same.index(cur) + 1}]' if len(same) > 1 else name)
            else:
                parts.append(name)
            cur = par
        self._xp[e] = '/' + '/'.join(reversed(parts))
        return self._xp[e]

    def descend(self, start, segs, use_filter):
        """Elements under `start` along the local-name segments `segs`."""
        cur = [start]
        for i, s in enumerate(segs):
            nxt = [c for e in cur for c in e if isinstance(c.tag, str) and local(c.tag) == s]
            # Passing down through the valuation PROPERTY list: stay on the properties the rule is about.
            if use_filter and nxt and i < len(segs) - 1 and '/'.join(self.path[nxt[0]]) == PROPERTY:
                nxt = [c for c in nxt if c.get('ValuationUseType') in use_filter]
            cur = nxt
            if not cur:
                break
        return cur

    def relative(self, anchor, target_path, use_filter=None, siblings=False):
        """Elements at full path `target_path` (container path, list of names) reachable from `anchor`:
        climb to the deepest common ancestor, then descend. Keeps lookups inside the same instance.
        siblings=True is for counting instances of a container the anchor is in: start from its parent."""
        ap = self.path[anchor]
        n = lcp(ap, target_path)
        if siblings and n == len(target_path):
            n -= 1
        e = anchor
        for _ in range(len(ap) - n):
            e = self.parent[e]
        return self.descend(e, target_path[n:], use_filter)


# ---------------------------------------------------------------- parsing

MAX_XML_IN_ZIP = 32 * 1024 * 1024


def from_zip(body: bytes):
    """UCDP takes a UAD 3.6 package: a ZIP holding the XML, the PDF and photos. Return the XML inside."""
    try:
        zf = zipfile.ZipFile(io.BytesIO(body))
        infos = [i for i in zf.infolist() if not i.is_dir() and i.filename.lower().endswith('.xml')
                 and not i.filename.startswith(('__MACOSX/', '.'))]
    except (zipfile.BadZipFile, ValueError):
        raise InputError('This looks like a ZIP file but it could not be opened.') from None
    if not infos:
        raise InputError('The ZIP file holds no .xml file. Send the UAD 3.6 package or the XML file itself.')
    found = []
    for info in infos:
        if info.file_size > MAX_XML_IN_ZIP:
            raise InputError(f'{info.filename[:80]} is over {MAX_XML_IN_ZIP // 1024 // 1024} MB uncompressed.')
        try:
            with zf.open(info) as fh:
                data = fh.read(MAX_XML_IN_ZIP + 1)
        except (zipfile.BadZipFile, RuntimeError, NotImplementedError, zlib.error):
            raise InputError(f'{info.filename[:80]} in the ZIP could not be read (encrypted or corrupt).') from None
        if len(data) > MAX_XML_IN_ZIP:
            raise InputError(f'{info.filename[:80]} is over {MAX_XML_IN_ZIP // 1024 // 1024} MB uncompressed.')
        if b'<MESSAGE' in data[:4096] or b':MESSAGE' in data[:4096]:
            found.append(data)
    if len(found) != 1:
        raise InputError('The ZIP file must hold exactly one UAD XML file (MESSAGE root); '
                         f'it holds {len(found)}. Send the XML file itself instead.')
    return found[0]


def parse(body: bytes):
    if not body or not body.strip():
        raise InputError('Send the appraisal XML as the request body.')
    packaged = body[:4] == b'PK\x03\x04'
    if packaged:
        body = from_zip(body)
    head = body[:4096]
    if head[:2] in (b'\xff\xfe', b'\xfe\xff') or head.startswith(b'\x00'):
        raise InputError('Send the XML as UTF-8.')
    if re.search(rb'<!DOCTYPE|<!ENTITY', body[:200_000], re.I) or re.search(rb'<!ENTITY', body, re.I):
        raise InputError('DOCTYPE and entity declarations are not accepted. UAD XML does not use them.')
    if body[:5] == b'%PDF-':
        raise InputError('This is a PDF. Send the UAD XML file, not the printed report.')
    try:
        root = ET.fromstring(body)
    except ET.ParseError as exc:
        raise InputError(f'The file is not well-formed XML ({exc}).') from None
    if root.tag != f'{{{MISMO_NS}}}MESSAGE':
        raise InputError('The root element must be MESSAGE in the MISMO residential namespace '
                         f'({MISMO_NS}). This does not look like a MISMO appraisal file.')
    ver = root.get('MISMOReferenceModelIdentifier') or ''
    if not ver.startswith('3.6'):
        raise InputError(f'MISMOReferenceModelIdentifier is {ver or "missing"}; UAD 3.6 files use 3.6.0366. '
                         'Files from the legacy UAD (MISMO 2.6) are not supported.')
    return root, ('zip' if packaged else 'xml'), len(body)


def report_type(doc):
    ids = [(e.text or '').strip() for e in doc.by_path.get(REPORT_ID_PATH, [])]
    ids = [i for i in ids if i]
    if not ids:
        raise InputError('ValuationReportContentIdentifier is missing, so the report type cannot be determined. '
                         'URAR files carry "URAR Delivery Specification v1.x" there.')
    rid = ids[0]
    for key, name in UNSUPPORTED.items():
        if key.lower() in rid.lower():
            raise InputError(f'This is a {name} ({rid}). This version validates URAR reports only.')
    for key, name in SUPPORTED.items():
        if rid.startswith(key):
            return name, rid
    raise InputError(f'Unsupported report type "{rid[:80]}". This version validates URAR reports only.')


# ---------------------------------------------------------------- three-valued logic

T, F, U = True, False, None


def k_and(vals):
    out = T
    for v in vals:
        if v is F:
            return F
        if v is U:
            out = U
    return out


def k_or(vals):
    out = F
    for v in vals:
        if v is T:
            return T
        if v is U:
            out = U
    return out


def every(results):
    results = list(results)
    if not results:
        return U
    if all(r is T for r in results):
        return T
    if all(r is F for r in results):
        return F
    return U


DATE = re.compile(r'^(\d{4})-(\d{2})-(\d{2})$')


def as_date(v):
    m = DATE.match(v or '')
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def as_num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def compare(op, a, b):
    """a, b strings. Numbers compare as numbers, ISO dates as dates, everything else as text (= and <> only)."""
    if op in ('=', '<>'):
        na, nb = as_num(a), as_num(b)
        eq = (na == nb) if (na is not None and nb is not None and not DATE.match(a or '')) else (a == b)
        return eq if op == '=' else not eq
    na, nb = as_num(a), as_num(b)
    if na is None or nb is None:
        da, db = as_date(a), as_date(b)
        if da is None or db is None:
            return U
        na, nb = da.toordinal(), db.toordinal()
    return {'<': na < nb, '>': na > nb, '<=': na <= nb, '>=': na >= nb}[op]


class Evaluator:
    def __init__(self, doc, rule, today):
        self.doc = doc
        self.rule = rule
        self.today = today
        self.use = set(rule.get('affected') or [])

    def values(self, ref, anchor):
        """Non-empty values of a data point or attribute, resolved nearest the anchor instance."""
        out = []
        for p in ref['paths']:
            segs = p.split('/')
            last = segs[-1]
            if last.startswith('@'):
                attr = last[1:]
                if attr == 'ValuationUseType':
                    v = self.doc.use_of(anchor)
                    if v is None and self.doc.path[anchor] == tuple(segs[:-1]):
                        v = anchor.get(attr)
                    if v is not None:
                        out.append((anchor, v))
                    continue
                key = '{http://www.w3.org/1999/xlink}' + attr.split(':', 1)[1] if attr.startswith('xlink:') else attr
                for e in self.doc.relative(anchor, segs[:-1], self.use):
                    v = (e.get(key) or '').strip()
                    if v:
                        out.append((e, v))
            else:
                for e in self.doc.relative(anchor, segs, self.use):
                    v = (e.text or '').strip()
                    if v:
                        out.append((e, v))
        return out

    def operand(self, node, anchor):
        if 'str' in node:
            return [(None, s) for s in node['str']]
        if 'num' in node:
            n = node['num']
            return [(None, str(int(n)) if n == int(n) else str(n))]
        return self.values(node, anchor)

    def instances(self, cpath, cond, anchor):
        """(true_count, unknown_count, true_elements) for instances of container cpath near anchor."""
        segs = cpath.split('/')
        found = self.doc.relative(anchor, segs, None if cpath == PROPERTY else self.use, siblings=True)
        t, u, hits = 0, 0, []
        for e in found:
            r = T if cond is None else self.ev(cond, e)
            if r is T:
                t += 1
                hits.append(e)
            elif r is U:
                u += 1
        return t, u, hits

    def ev(self, node, anchor):
        op = node[0]
        if op == 'and':
            return k_and(self.ev(n, anchor) for n in node[1:])
        if op == 'or':
            return k_or(self.ev(n, anchor) for n in node[1:])
        if op == 'cmp':
            _, cop, lhs, rhs = node
            left = self.operand(lhs, anchor)
            right = self.operand(rhs, anchor)
            if not left or not right:
                # A value that was not provided equals nothing; every other comparison is unknown.
                return F if cop == '=' and 'str' in rhs else U
            if 'str' in rhs and len(rhs['str']) > 1:
                alts = rhs['str']
                return every((v in alts) if cop == '=' else (v not in alts) for _, v in left)
            return every(compare(cop, a, b) for _, a in left for _, b in right)
        if op == 'missing':
            return T if not self.values(node[1], anchor) else F
        if op == 'present':
            return F if not self.values(node[1], anchor) else T
        if op == 'count':
            _, cpath, cond, cop, n = node
            t, u, _ = self.instances(cpath, cond, anchor)
            if cop == '==':
                return F if t > n else (U if u else (T if t == n else F))
            if cop == '>':
                return T if t > n else (F if t + u <= n else U)
            if cop == '!=':
                if u == 0:
                    return T if t != n else F
                return T if t > n else U
            return U
        if op == 'counteq':
            _, cop, lhs, cpath, cond = node
            vals = self.values(lhs, anchor)
            if not vals:
                return U
            t, u, _ = self.instances(cpath, cond, anchor)
            if u:
                return U
            res = every(compare('=', v, str(t)) for _, v in vals)
            if res is U:
                return U
            return res if cop == '=' else (not res)
        if op == 'unique':
            _, ref, cpath, cond = node
            t, u, hits = self.instances(cpath, cond, anchor)
            seen = Counter()
            for inst in hits:
                for _, v in self.values(ref, inst)[:1]:
                    seen[v] += 1
            if any(c > 1 for c in seen.values()):
                return T
            return U if u else F
        if op == 'datefmt':
            vals = self.values(node[1], anchor)
            return T if any(not format_ok('Date', node[2], v) for _, v in vals) else F
        if op == 'future':
            ds = [as_date(v) for _, v in self.values(node[1], anchor)]
            if any(d is None for d in ds):
                return U
            return T if any(d > self.today for d in ds) else F
        if op == 'older':
            ds = [as_date(v) for _, v in self.values(node[1], anchor)]
            if any(d is None for d in ds):
                return U
            return T if any((self.today - d).days > node[2] for d in ds) else F
        if op == 'zip':
            vals = self.values(node[1], anchor)
            return T if any(not re.fullmatch(r'\d{5}(-\d{4})?', v) for _, v in vals) else F
        if op == 'state':
            vals = self.values(node[1], anchor)
            return T if any(v not in STATE_CODES for _, v in vals) else F
        return U

    def anchors(self):
        a = self.rule['anchor']
        found = self.doc.by_path.get(a['path'], [])
        if self.use and (a['path'] == PROPERTY or a['path'].startswith(PROPERTY + '/')):
            found = [e for e in found if self.doc.use_of(e) in self.use]
        if a['with'] is not None:
            found = [e for e in found if self.ev(a['with'], e) is T]
        return found


# ---------------------------------------------------------------- delivery specification checks (A-1)

def entries_for(doc, e, entries):
    use = doc.use_of(e)
    if use is None:
        return entries
    scoped = [x for x in entries if not x['use'] or use in x['use']]
    return scoped or entries


NUM_DET = re.compile(r'^([+\-±]?)(\d+)\.(\d+)$')


def format_ok(fmt, det, v):
    if fmt == 'Boolean':
        return v in ('true', 'false')
    if fmt == 'Date':
        pat = {'YYYY': r'\d{4}', 'YYYY-MM': r'\d{4}-(0[1-9]|1[0-2])', 'YYYY-MM-DD': None}.get(det or 'YYYY-MM-DD', None)
        return as_date(v) is not None if pat is None else re.fullmatch(pat, v) is not None
    if fmt == 'Datetime':
        return re.fullmatch(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:\d{2})?', v) is not None \
            and as_date(v[:10]) is not None
    if fmt in ('Numeric', 'Amount'):
        m = NUM_DET.match(det or '')
        num = re.fullmatch(r'([+-]?)(\d*)(?:\.(\d*))?', v)
        if not num or not (num.group(2) or num.group(3)):
            return False
        if not m:
            return True
        sign, ints, decs = m.group(1), int(m.group(2)), int(m.group(3))
        if num.group(1) == '-' and sign in ('+', '') and as_num(v) != 0:
            return False
        if sign == '-' and num.group(1) != '-' and as_num(v) != 0:
            return False
        if len(num.group(2).lstrip('0')) > ints:
            return False
        return len(num.group(3) or '') <= decs
    if fmt == 'String':
        return not det.isdigit() or len(v) <= int(det)
    return True


FORMAT_HINT = {
    'Boolean': 'must be lowercase "true" or "false"',
    'Date': 'must be a date in {det} format',
    'Datetime': 'must be a date and time like 2026-01-15T14:30:00Z',
    'Numeric': 'must be a number within the delivery specification precision ({det})',
    'Amount': 'must be an amount within the delivery specification precision ({det})',
    'String': 'is longer than the {det} characters the delivery specification allows',
}


def spec_checks(doc, add):
    R = rules()
    containers, dps = R['containers'], R['datapoints']
    unknown = {}
    # every element: known path, enumerations, formats
    for path, elems in doc.by_path.items():
        if path in dps:
            for e in elems:
                if len(e):
                    continue
                v = (e.text or '').strip()
                ents = entries_for(doc, e, dps[path])
                name = path.rsplit('/', 1)[1]
                if not v:
                    add('error', 'A1-EMPTY', doc.xpath(e), f'{name} is present but empty. Omit a data point rather than '
                        'deliver it without a value.', ents[0]['id'])
                    continue
                # Lists are closed only for Enumerated and Boolean data points. A String data point with a listed
                # value (e.g. OutbuildingTypeOtherDescription "ADUGarage") also accepts free text.
                closed = all(en['enum'] and en['fmt'] in ('Enumerated', 'Boolean') for en in ents)
                enums = sorted({x for en in ents for x in en['enum']}) if closed else []
                if enums and v not in enums:
                    add('error', 'A1-ENUM', doc.xpath(e), f'{name} = "{v[:40]}" is not a supported UAD value. '
                        f'Supported: {", ".join(enums[:12])}{"..." if len(enums) > 12 else ""}.', ents[0]['id'])
                    continue
                fmts = [(en['fmt'], en['det']) for en in ents if en['fmt']]
                if fmts and not any(format_ok(f, d, v) for f, d in fmts):
                    f, d = fmts[0]
                    add('error', 'A1-FORMAT', doc.xpath(e), f'{name} {FORMAT_HINT.get(f, "has the wrong format").format(det=d)}.',
                        ents[0]['id'])
        elif path not in containers:
            unknown.setdefault(path, elems)
        # attributes with supported enumerations
        for e in elems:
            for attr, v in e.attrib.items():
                if attr.startswith('{'):
                    continue  # xlink labels are identifiers; A-1 lists placeholder patterns such as ROLE_n, not values
                key = path + '/@' + attr
                ents = dps.get(key)
                if not ents:
                    continue
                # Attribute rows are split by use type (@ValuationUseType itself defines it): use them all.
                enums = sorted({x for en in ents for x in en['enum']}) if all(en['enum'] for en in ents) else []
                if enums and v not in enums:
                    add('error', 'A1-ENUM', doc.xpath(e) + '/@' + local(attr), f'@{local(attr)} = "{v[:40]}" is not a supported '
                        f'UAD value. Supported: {", ".join(enums[:12])}{"..." if len(enums) > 12 else ""}.', ents[0]['id'])
    for path, elems in sorted(unknown.items()):
        parent = path.rsplit('/', 1)[0]
        if parent in unknown:
            continue  # report the outermost unknown element only
        add('warning', 'A1-UNKNOWN', doc.xpath(elems[0]),
            f'{path.rsplit("/", 1)[1]} is not part of the UAD 3.6 URAR delivery specification at this location'
            f'{f" ({len(elems)} occurrences)" if len(elems) > 1 else ""}. UCDP may reject or ignore it.', None)

    # Required (R) data points in each container instance that is present. A-1 lists one row per context
    # (a ROLE for the appraiser, a ROLE for the lender, ...). The path alone cannot tell those contexts
    # apart, so a data point is only treated as required when every row that applies to it says R.
    for key, ents in dps.items():
        if not any(en['req'] == 'R' for en in ents):
            continue
        parent, leaf = key.rsplit('/', 1)
        if containers.get(parent, {}).get('contexts', 1) > 1:
            continue
        for e in doc.by_path.get(parent, []):
            applicable = entries_for(doc, e, ents)
            if not all(en['req'] == 'R' for en in applicable):
                continue
            use = doc.use_of(e)
            if use is not None and not any(not en['use'] or use in en['use'] for en in applicable):
                continue
            if leaf.startswith('@'):
                attr = leaf[1:]
                k = '{http://www.w3.org/1999/xlink}' + attr.split(':', 1)[1] if attr.startswith('xlink:') else attr
                ok = bool((e.get(k) or '').strip())
            else:
                ok = any((c.text or '').strip() for c in e if local(c.tag) == leaf)
            if not ok:
                add('error', 'A1-REQUIRED', doc.xpath(e) + '/' + leaf,
                    f'{leaf} is required in every {parent.split("/")[-1]} by the delivery specification.', applicable[0]['id'])

    # cardinality: instances of a container under one parent
    for path, c in containers.items():
        if path == 'MESSAGE' or (c['max'] is None and not c.get('maxByUse')):
            continue
        per_parent = Counter(doc.parent[e] for e in doc.by_path.get(path, []))
        for par, n in per_parent.items():
            limit = c.get('maxByUse', {}).get(doc.use_of(par), c['max'])
            if limit is not None and n > limit:
                name = path.rsplit('/', 1)[1]
                add('error', 'A1-CARDINALITY', doc.xpath(par) + '/' + name,
                    f'{name} occurs {n} times here; the delivery specification allows at most {limit}.', None)


# ---------------------------------------------------------------- entry point

def validate(body: bytes, today=None):
    today = today or dt.datetime.now(dt.timezone.utc).date()
    root, container, xml_bytes = parse(body)
    doc = Doc(root)
    rtype, rid = report_type(doc)
    R = rules()

    findings = []
    seen = set()

    def add(sev, rule_id, path, msg, ref):
        k = (rule_id, path)
        if k in seen:
            return
        seen.add(k)
        f = {'severity': sev, 'ruleId': rule_id, 'path': path, 'message': msg}
        if ref:
            f['specReference'] = ref
        findings.append(f)

    spec_checks(doc, add)

    evaluated = 0
    for rule in R['rules']:
        ev = Evaluator(doc, rule, today)
        try:
            anchors = ev.anchors()
        except RecursionError:
            continue
        evaluated += 1
        tpath = (rule['target']['path'] + '/' + rule['target']['name']).split('/') if rule['target']['name'] else None
        for a in anchors:
            if ev.ev(rule['expr'], a) is not T:
                continue
            path = None
            if tpath:
                hits = doc.relative(a, tpath, ev.use)
                if hits:
                    path = doc.xpath(hits[0])
                else:
                    ap = doc.path[a]
                    n = lcp(ap, tpath)
                    base = a
                    for _ in range(len(ap) - n):
                        base = doc.parent[base]
                    path = doc.xpath(base) + ''.join('/' + s for s in tpath[n:])
            add('error' if rule['sev'].startswith('Fatal') else 'warning', rule['id'], path or doc.xpath(a), rule['msg'], rule['uid'])

    order = {'error': 0, 'warning': 1}
    findings.sort(key=lambda f: (order[f['severity']], f['ruleId'], f['path']))
    counts = Counter(f['severity'] for f in findings)
    status = 'FAIL' if counts['error'] else ('WARN' if counts['warning'] else 'PASS')
    props = Counter(e.get('ValuationUseType') or 'unspecified' for e in doc.by_path.get(PROPERTY, []))
    not_impl = R['notImplemented']
    return {
        'schemaVersion': 1,
        'status': status,
        'reportType': rtype,
        'reportContentIdentifier': rid[:120],
        'mismoReferenceModelIdentifier': root.get('MISMOReferenceModelIdentifier'),
        'input': {'container': container, 'xmlBytes': xml_bytes,
                  'note': 'Only the XML is validated. A package\'s PDF and photos are not checked.' if container == 'zip' else None},
        'properties': dict(sorted(props.items())),
        'findingCount': len(findings),
        'findingCounts': {'error': counts['error'], 'warning': counts['warning']},
        'ruleCounts': dict(sorted(Counter(f['ruleId'] for f in findings).items())),
        'findings': findings[:MAX_FINDINGS],
        'findingsTruncated': len(findings) > MAX_FINDINGS,
        'coverage': {
            'complianceRulesTotal': len(R['rules']) + len(not_impl),
            'complianceRulesEvaluated': evaluated,
            'complianceRulesNotImplemented': sorted({x['id'] for x in not_impl}),
            'deliverySpecChecks': ['A1-UNKNOWN', 'A1-ENUM', 'A1-FORMAT', 'A1-EMPTY', 'A1-REQUIRED', 'A1-CARDINALITY'],
            'sampling': 'none: every element in the file is checked',
        },
        'sources': {k: {'title': v['title'], 'sheet': v['sheet']} for k, v in R['sources'].items()},
        'inputSha256': hashlib.sha256(body).hexdigest(),
        'scope': ('Structural checks against the GSE-published UAD 3.6 URAR delivery specification and compliance '
                  'rules. A PASS does not mean UCDP acceptance, and this is not legal or compliance advice.'),
    }
