import { hydrateRoot, createRoot } from 'react-dom/client';
import './site.css';

// Per-page code splitting: each page loads only its own component. Keep the keys in sync with
// routes.jsx (scripts/check-site.mjs fails the build if a prerendered page has no loader here).
export const LOADERS = {
  '/': () => import('./pages/Home.jsx'),
  '/apis': () => import('./pages/Catalog.jsx'),
  '/apis/clinical-trial-table-validator': () => import('./pages/ClinicalApi.jsx'),
  '/apis/hospital-mrf-validator': () => import('./pages/MrfApi.jsx'),
  '/apis/uad-36-appraisal-validator': () => import('./pages/UadApi.jsx'),
  '/apis/pbj-staffing-qa': () => import('./pages/PbjApi.jsx'),
  '/apis/wh347-payroll-precheck': () => import('./pages/Wh347Api.jsx'),
  '/apis/pecos-enrollment-precheck': () => import('./pages/PecosApi.jsx'),
  '/apis/cobra-notice-qa': () => import('./pages/CobraApi.jsx'),
  '/apis/cmmc-self-assessment-validator': () => import('./pages/CmmcApi.jsx'),
  '/tools/davis-bacon-overtime-calculator': () => import('./pages/OvertimeCalculator.jsx'),
  '/tools/davis-bacon-fringe-calculator': () => import('./pages/FringeCalculator.jsx'),
  '/tools/davis-bacon-apprentice-checker': () => import('./pages/ApprenticeChecker.jsx'),
  '/tools/pbj-preflight-checks': () => import('./pages/PbjPreflight.jsx'),
  '/tools': () => import('./pages/Tools.jsx'),
  '/tools/i9-section2-deadline-calculator': () => import('./pages/I9Deadline.jsx'),
  '/tools/cobra-deadline-calculator': () => import('./pages/CobraDeadline.jsx'),
  '/tools/final-paycheck-deadline': () => import('./pages/FinalPaycheck.jsx'),
  '/tools/contractor-vs-employee-check': () => import('./pages/ContractorCheck.jsx'),
  '/tools/mechanics-lien-deadline-calculator': () => import('./pages/LienDeadline.jsx'),
  '/tools/uad36-preflight-checklist': () => import('./pages/UadPreflight.jsx'),
  '/tools/cpsc-efiling-readiness-checklist': () => import('./pages/CpscChecklist.jsx'),
  '/docs': () => import('./pages/Docs.jsx'),
  '/docs/clinical-trial-table-validator': () => import('./pages/DocsClinical.jsx'),
  '/docs/hospital-mrf-validator': () => import('./pages/DocsMrf.jsx'),
  '/docs/uad-36-appraisal-validator': () => import('./pages/DocsUad.jsx'),
  '/docs/pbj-staffing-qa': () => import('./pages/DocsPbj.jsx'),
  '/docs/wh347-payroll-precheck': () => import('./pages/DocsWh347.jsx'),
  '/docs/pecos-enrollment-precheck': () => import('./pages/DocsPecos.jsx'),
  '/docs/cobra-notice-qa': () => import('./pages/DocsCobra.jsx'),
  '/docs/cmmc-self-assessment-validator': () => import('./pages/DocsCmmc.jsx'),
  '/guides': () => import('./pages/Guides.jsx'),
  '/guides/hospital-price-transparency-file-requirements-2026': () => import('./pages/MrfGuide.jsx'),
  '/guides/uad-3-6-requirements-2026': () => import('./pages/UadGuide.jsx'),
  '/guides/clinical-trial-data-quality-checks': () => import('./pages/ClinicalGuide.jsx'),
  '/guides/uad36-fatal-findings-explained': () => import('./pages/uad/uad36-fatal-findings-explained.jsx'),
  '/guides/ucdp-not-successful-meaning': () => import('./pages/uad/ucdp-not-successful-meaning.jsx'),
  '/guides/uad36-warning-vs-fatal': () => import('./pages/uad/uad36-warning-vs-fatal.jsx'),
  '/guides/uad36-basement-fields-hard-stop': () => import('./pages/uad/uad36-basement-fields-hard-stop.jsx'),
  '/guides/uad36-location-view-codes-rejected': () => import('./pages/uad/uad36-location-view-codes-rejected.jsx'),
  '/guides/uad36-concession-mismatch': () => import('./pages/uad/uad36-concession-mismatch.jsx'),
  '/guides/uad36-address-usps-flag': () => import('./pages/uad/uad36-address-usps-flag.jsx'),
  '/guides/ucdp-not-successful-vs-rejected': () => import('./pages/uad/ucdp-not-successful-vs-rejected.jsx'),
  '/guides/pbj-error-minus-1025': () => import('./pages/pbj/pbj-error-minus-1025.jsx'),
  '/guides/pbj-error-4025': () => import('./pages/pbj/pbj-error-4025.jsx'),
  '/guides/pbj-error-3679': () => import('./pages/pbj/pbj-error-3679.jsx'),
  '/guides/pbj-error-3676': () => import('./pages/pbj/pbj-error-3676.jsx'),
  '/guides/pbj-error-4016': () => import('./pages/pbj/pbj-error-4016.jsx'),
  '/guides/pbj-zero-rn-days': () => import('./pages/guides/pbj-zero-rn-days.jsx'),
  '/guides/uad36-rule-uad1189': () => import('./pages/guides/uad36-rule-uad1189.jsx'),
  '/guides/uad36-rule-uad1001': () => import('./pages/guides/uad36-rule-uad1001.jsx'),
  '/guides/pbj-file-rejected': () => import('./pages/guides/pbj-file-rejected.jsx'),
  '/guides/how-to-fix-ucdp-errors': () => import('./pages/guides/how-to-fix-ucdp-errors.jsx'),
  '/guides/wh347-apprentice-reporting': () => import('./pages/guides/wh347-apprentice-reporting.jsx'),
  '/guides/wh347-statement-of-compliance': () => import('./pages/guides/wh347-statement-of-compliance.jsx'),
  '/guides/wh347-common-mistakes': () => import('./pages/guides/wh347-common-mistakes.jsx'),
  '/guides/davis-bacon-fringe-annualization': () => import('./pages/guides/davis-bacon-fringe-annualization.jsx'),
  '/guides/davis-bacon-weighted-overtime': () => import('./pages/guides/davis-bacon-weighted-overtime.jsx'),
  '/guides/pecos-returned-for-corrections': () => import('./pages/guides/pecos-returned-for-corrections.jsx'),
  '/guides/npi-not-active-nppes': () => import('./pages/guides/npi-not-active-nppes.jsx'),
  '/guides/855i-rejection-reasons': () => import('./pages/guides/855i-rejection-reasons.jsx'),
  '/guides/cobra-election-notice-requirements': () => import('./pages/guides/cobra-election-notice-requirements.jsx'),
  '/guides/cobra-notice-deadlines': () => import('./pages/guides/cobra-notice-deadlines.jsx'),
  '/guides/sprs-score-calculation': () => import('./pages/guides/sprs-score-calculation.jsx'),
  '/guides/cmmc-poam-rules': () => import('./pages/guides/cmmc-poam-rules.jsx'),
  '/guides/cobra-penalty-110-per-day': () => import('./pages/guides/cobra-penalty-110-per-day.jsx'),
  '/guides/medicare-revalidation-missed-deadline': () => import('./pages/guides/medicare-revalidation-missed-deadline.jsx'),
  '/guides/what-is-cpsc-efiling': () => import('./pages/guides/what-is-cpsc-efiling.jsx'),
  '/account': () => import('./pages/Account.jsx'),
  '/unsubscribe': () => import('./pages/Unsubscribe.jsx'),
  '/contact': () => import('./Contact.jsx'),
  '/privacy': () => import('./Privacy.jsx'),
  '/terms': () => import('./Terms.jsx'),
  '/404': () => import('./NotFound.jsx'),
};

const p = window.location.pathname;
const path = p.length > 1 && p.endsWith('/') ? p.slice(0, -1) : p;
const { default: Component } = await (LOADERS[path] || LOADERS['/404'])();
const root = document.getElementById('root');
if (root.firstElementChild) hydrateRoot(root, <Component />);
else createRoot(root).render(<Component />);
